logging:
  level:
    com.github.peacetrue: trace
#    org.springframework: debug

peacetrue:
  init:
    schema-script-locations:
      'com.github.peacetrue.member.Member': /schema-member-mysql.sql
